import { api } from './client';

export const productApi = {
  listProducts: (category) => api.request(`/products${category ? `?category=${encodeURIComponent(category)}` : ''}`),
  getProduct: (id) => api.request(`/products/${id}`),
  getProductBySlug: (slug) => api.request(`/products/slug/${encodeURIComponent(slug)}`),
  listAdminProducts: () => api.request('/admin/products?summary=true'),
  createProduct: (payload) => api.request('/products', { method: 'POST', body: payload }),
  updateProduct: (id, payload) => api.request(`/products/${id}`, { method: 'PATCH', body: payload }),
  deactivateProduct: (id) => api.request(`/products/${id}`, { method: 'DELETE' }),
  deleteProduct: (id) => api.request(`/products/${id}/permanent`, { method: 'DELETE' }),
  listCart: () => api.request('/cart'),
  addToCart: (productId, quantity = 1) => api.request('/cart', { method: 'POST', body: { productId, quantity } }),
  removeFromCart: (productId) => api.request(`/cart/${productId}`, { method: 'DELETE' }),
  listWishlist: () => api.request('/wishlist'),
  addToWishlist: (productId) => api.request(`/wishlist/${productId}`, { method: 'POST' }),
  removeFromWishlist: (productId) => api.request(`/wishlist/${productId}`, { method: 'DELETE' }),
  listGames: () => api.request('/games'),
  // added missing listApps so Home.jsx can call productApi.listApps
  listApps: () => api.request('/apps'),
  getGame: (id) => api.request(`/games/${id}`),
  updateGame: (id, payload) => api.request(`/games/${id}`, { method: 'PATCH', body: payload }),
  deleteGame: (id) => api.request(`/games/${id}`, { method: 'DELETE' }),
  getApp: (id) => api.request(`/apps/${id}`),
  updateApp: (id, payload) => api.request(`/apps/${id}`, { method: 'PATCH', body: payload }),
  deleteApp: (id) => api.request(`/apps/${id}`, { method: 'DELETE' }),
  getPowerpoint: (id) => api.request(`/powerpoints/${id}`),
  listPowerpoints: () => api.request('/powerpoints'),
  updatePowerpoint: (id, payload) => api.request(`/powerpoints/${id}`, { method: 'PATCH', body: payload }),
  deletePowerpoint: (id) => api.request(`/powerpoints/${id}`, { method: 'DELETE' }),
  createGame: (payload) => api.request('/games', { method: 'POST', body: payload }),
  createApp: (payload) => api.request('/apps', { method: 'POST', body: payload }),
  createPowerpoint: (payload) => api.request('/powerpoints', { method: 'POST', body: payload }),
};
